// <auto-generated />
using System;
using DACS2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DACS2.Data.Migrations
{
    [DbContext(typeof(DACS2DbContext))]
    [Migration("20221111072526_themcot")]
    partial class themcot
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DACS2.Data.Entities.CategoryNews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<string>("NewsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CategoryNews");
                });

            modelBuilder.Entity("DACS2.Data.Entities.CategoryProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("pathImg")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CategoryProduct");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("ColorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.ToTable("Color");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Designs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesignsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.ToTable("Designs");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("IdDesign")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("pathImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.ToTable("Image");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<string>("NameCustomer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalMoney")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("DACS2.Data.Entities.InvoiceDetails", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdInvoice")
                        .HasColumnType("int");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Money")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id", "IdInvoice");

                    b.HasIndex("IdInvoice");

                    b.ToTable("InvoiceDetails");
                });

            modelBuilder.Entity("DACS2.Data.Entities.MstPerMission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MstPerMission");

                    b.HasData(
                        new
                        {
                            Id = 9203,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm quyền",
                            GroupName = "Quản lý phân quyền",
                            Table = "Role"
                        },
                        new
                        {
                            Id = 9208,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa quyền",
                            GroupName = "Quản lý phân quyền",
                            Table = "Role"
                        },
                        new
                        {
                            Id = 9204,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa quyền",
                            GroupName = "Quản lý phân quyền",
                            Table = "Role"
                        },
                        new
                        {
                            Id = 9202,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết quyền",
                            GroupName = "Quản lý phân quyền",
                            Table = "Role"
                        },
                        new
                        {
                            Id = 9201,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách quyền",
                            GroupName = "Quản lý phân quyền",
                            Table = "Role"
                        },
                        new
                        {
                            Id = 2003,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm thể loại tin thức",
                            GroupName = "Quản lý Thể loại tin tức",
                            Table = "CategoryNews"
                        },
                        new
                        {
                            Id = 2008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa thể loại tin thức",
                            GroupName = "Quản lý Thể loại tin tức",
                            Table = "CategoryNews"
                        },
                        new
                        {
                            Id = 2004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa thể loại tin thức",
                            GroupName = "Quản lý Thể loại tin tức",
                            Table = "CategoryNews"
                        },
                        new
                        {
                            Id = 2001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách thể loại tin thức",
                            GroupName = "Quản lý Thể loại tin tức",
                            Table = "CategoryNews"
                        },
                        new
                        {
                            Id = 3003,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm thể loại sản phẩm",
                            GroupName = "Quản lý thể loại sản phẩm",
                            Table = "CategoryProduct"
                        },
                        new
                        {
                            Id = 3008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa thể loại sản phẩm",
                            GroupName = "Quản lý thể loại sản phẩm",
                            Table = "CategoryProduct"
                        },
                        new
                        {
                            Id = 3004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa thể loại sản phẩm",
                            GroupName = "Quản lý thể loại sản phẩm",
                            Table = "CategoryProduct"
                        },
                        new
                        {
                            Id = 3001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách thể loại sản phẩm",
                            GroupName = "Quản lý thể loại sản phẩm",
                            Table = "CategoryProduct"
                        },
                        new
                        {
                            Id = 4003,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm màu sản phẩm",
                            GroupName = "Quản lý màu sản phẩm",
                            Table = "Color"
                        },
                        new
                        {
                            Id = 4008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa màu sản phẩm",
                            GroupName = "Quản lý màu sản phẩm",
                            Table = "Color"
                        },
                        new
                        {
                            Id = 4004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa màu sản phẩm",
                            GroupName = "Quản lý màu sản phẩm",
                            Table = "Color"
                        },
                        new
                        {
                            Id = 4001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách màu sản phẩm",
                            GroupName = "Quản lý màu sản phẩm",
                            Table = "Color"
                        },
                        new
                        {
                            Id = 5003,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm  kiểu dáng sản phẩm",
                            GroupName = "Quản lý kiểu dáng sản phẩm",
                            Table = "Designs"
                        },
                        new
                        {
                            Id = 5008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa kiểu dáng sản phẩm",
                            GroupName = "Quản lý kiểu dáng sản phẩm",
                            Table = "Designs"
                        },
                        new
                        {
                            Id = 5004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa kiểu dáng sản phẩm",
                            GroupName = "Quản lý kiểu dáng sản phẩm",
                            Table = "Designs"
                        },
                        new
                        {
                            Id = 5001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách kiểu dáng sản phẩm",
                            GroupName = "Quản lý kiểu dáng sản phẩm",
                            Table = "Designs"
                        },
                        new
                        {
                            Id = 6003,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm  hình ảnh sản phẩm",
                            GroupName = "Quản lý hình sản phẩm",
                            Table = "Image"
                        },
                        new
                        {
                            Id = 6008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa hình ảnh sản phẩm",
                            GroupName = "Quản lý hình sản phẩm",
                            Table = "Image"
                        },
                        new
                        {
                            Id = 6004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa hình ảnh sản phẩm",
                            GroupName = "Quản lý hình sản phẩm",
                            Table = "Image"
                        },
                        new
                        {
                            Id = 6001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách hình ảnh sản phẩm",
                            GroupName = "Quản lý hình sản phẩm",
                            Table = "Image"
                        },
                        new
                        {
                            Id = 7008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa đơn hàng",
                            GroupName = "Quản lý giỏ hàng",
                            Table = "Invoice"
                        },
                        new
                        {
                            Id = 7004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa đơn hàng",
                            GroupName = "Quản lý giỏ hàng",
                            Table = "Invoice"
                        },
                        new
                        {
                            Id = 7001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách đơn hàng",
                            GroupName = "Quản lý giỏ hàng",
                            Table = "Invoice"
                        },
                        new
                        {
                            Id = 7002,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem  đơn hàng",
                            GroupName = "Quản lý giỏ hàng",
                            Table = "Invoice"
                        },
                        new
                        {
                            Id = 8008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa đơn hàng",
                            GroupName = "Quản lý giỏ hàng",
                            Table = "InvoiceDetails"
                        },
                        new
                        {
                            Id = 8001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem chi tiết danh sách đơn hàng",
                            GroupName = "Quản lý giỏ hàng",
                            Table = "InvoiceDetails"
                        },
                        new
                        {
                            Id = 9003,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm tin tức",
                            GroupName = "Quản lý tin tức",
                            Table = "News"
                        },
                        new
                        {
                            Id = 9008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa tin tức",
                            GroupName = "Quản lý tin tức",
                            Table = "News"
                        },
                        new
                        {
                            Id = 9004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa tin tức",
                            GroupName = "Quản lý tin tức",
                            Table = "News"
                        },
                        new
                        {
                            Id = 9001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách tin tức",
                            GroupName = "Quản lý tin tức",
                            Table = "News"
                        },
                        new
                        {
                            Id = 9002,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem tin tức",
                            GroupName = "Quản lý tin tức",
                            Table = "News"
                        },
                        new
                        {
                            Id = 9103,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm sản phẩm",
                            GroupName = "Quản lý sản phẩm",
                            Table = "Product"
                        },
                        new
                        {
                            Id = 9108,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa sản phẩm",
                            GroupName = "Quản lý sản phẩm",
                            Table = "Product"
                        },
                        new
                        {
                            Id = 9104,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa sản phẩm",
                            GroupName = "Quản lý sản phẩm",
                            Table = "Product"
                        },
                        new
                        {
                            Id = 9101,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách sản phẩm",
                            GroupName = "Quản lý sản phẩm",
                            Table = "Product"
                        },
                        new
                        {
                            Id = 9102,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem sản phẩm",
                            GroupName = "Quản lý sản phẩm",
                            Table = "Product"
                        },
                        new
                        {
                            Id = 1003,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm tài khoản",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        },
                        new
                        {
                            Id = 1008,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa tài khoản",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        },
                        new
                        {
                            Id = 1004,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa tài khoản",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        },
                        new
                        {
                            Id = 1001,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách tài khoản",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        },
                        new
                        {
                            Id = 1007,
                            Code = "UNBLOCK",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Mở khóa tài khoản",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        },
                        new
                        {
                            Id = 1006,
                            Code = "BLOCK",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Khóa tài khoản",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        },
                        new
                        {
                            Id = 1005,
                            Code = "UPDATE_PWD",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Đổi mật khẩu",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        },
                        new
                        {
                            Id = 1002,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem tài khoản",
                            GroupName = "Quản lý tài khoản",
                            Table = "User"
                        },
                        new
                        {
                            Id = 9503,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm mã giảm giá",
                            GroupName = "Quản lý mã giảm giá",
                            Table = "Voucher"
                        },
                        new
                        {
                            Id = 9508,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa mã giảm giá",
                            GroupName = "Quản lý mã giảm giá",
                            Table = "Voucher"
                        },
                        new
                        {
                            Id = 9504,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa Mã giảm giá",
                            GroupName = "Quản lý mã giảm giá",
                            Table = "Voucher"
                        },
                        new
                        {
                            Id = 9501,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách mã",
                            GroupName = "Quản lý mã giảm giá",
                            Table = "Voucher"
                        },
                        new
                        {
                            Id = 9502,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem mã giảm giá",
                            GroupName = "Quản lý mã giảm giá",
                            Table = "Voucher"
                        },
                        new
                        {
                            Id = 9703,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm chính sách",
                            GroupName = "Quản lý chính sách",
                            Table = "Policy"
                        },
                        new
                        {
                            Id = 9708,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa chính sách",
                            GroupName = "Quản lý chính sách",
                            Table = "Policy"
                        },
                        new
                        {
                            Id = 9704,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa chính sách",
                            GroupName = "Quản lý chính sách",
                            Table = "Policy"
                        },
                        new
                        {
                            Id = 9701,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách chính sách",
                            GroupName = "Quản lý chính sách",
                            Table = "Policy"
                        },
                        new
                        {
                            Id = 9903,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm thông tin web",
                            GroupName = "Quản lý system",
                            Table = "System"
                        },
                        new
                        {
                            Id = 9908,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa thông tin",
                            GroupName = "Quản lý system",
                            Table = "System"
                        },
                        new
                        {
                            Id = 9904,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa thông tin",
                            GroupName = "Quản lý system",
                            Table = "System"
                        },
                        new
                        {
                            Id = 9902,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem thông tin",
                            GroupName = "Quản lý system",
                            Table = "System"
                        },
                        new
                        {
                            Id = 9803,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm nhà cung cấp",
                            GroupName = "Quản lý nhà cung cấp",
                            Table = "Supplier"
                        },
                        new
                        {
                            Id = 9808,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa nhà cung cấp",
                            GroupName = "Quản lý nhà cung cấp",
                            Table = "Supplier"
                        },
                        new
                        {
                            Id = 9804,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa nhà cung cấp",
                            GroupName = "Quản lý nhà cung cấp",
                            Table = "Supplier"
                        },
                        new
                        {
                            Id = 9801,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách nhà cung cấp",
                            GroupName = "Quản lý nhà cung cấp",
                            Table = "Supplier"
                        },
                        new
                        {
                            Id = 1903,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm phản hồi",
                            GroupName = "Quản lý phản hồi",
                            Table = "Report"
                        },
                        new
                        {
                            Id = 1908,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa phản hồi",
                            GroupName = "Quản lý phản hồi",
                            Table = "Report"
                        },
                        new
                        {
                            Id = 1904,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa phản hồi",
                            GroupName = "Quản lý phản hồi",
                            Table = "Report"
                        },
                        new
                        {
                            Id = 1901,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sách phản hồi",
                            GroupName = "Quản lý phản hồi",
                            Table = "Report"
                        },
                        new
                        {
                            Id = 1902,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem phản hồi",
                            GroupName = "Quản lý phản hồi",
                            Table = "Report"
                        },
                        new
                        {
                            Id = 9403,
                            Code = "CREATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Thêm Size",
                            GroupName = "Quản lý Size",
                            Table = "Size"
                        },
                        new
                        {
                            Id = 9408,
                            Code = "DELETE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xóa Size",
                            GroupName = "Quản lý Size",
                            Table = "Size"
                        },
                        new
                        {
                            Id = 9404,
                            Code = "UPDATE",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Sửa Size",
                            GroupName = "Quản lý Size",
                            Table = "Size"
                        },
                        new
                        {
                            Id = 9401,
                            Code = "VIEW_LIST",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem danh sáchSize",
                            GroupName = "Quản lý Size",
                            Table = "Size"
                        },
                        new
                        {
                            Id = 9402,
                            Code = "VIEW_DETAIL",
                            CreateAt = new DateTime(2021, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Desc = "Xem Size",
                            GroupName = "Quản lý Size",
                            Table = "Size"
                        });
                });

            modelBuilder.Entity("DACS2.Data.Entities.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int>("IdCategoryNew")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("pathImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoryNew");

                    b.ToTable("News");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Policy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<string>("PolicyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Policy");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int>("IdProductCategory")
                        .HasColumnType("int");

                    b.Property<int>("IdSuplier")
                        .HasColumnType("int");

                    b.Property<int?>("ImportPrice")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sold")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("pathImgP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdProductCategory");

                    b.HasIndex("IdSuplier");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Report");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("DACS2.Data.Entities.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int>("MStPermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MStPermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<string>("SizeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdProduct");

                    b.ToTable("Size");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2022, 11, 11, 14, 25, 25, 688, DateTimeKind.Local).AddTicks(5155),
                            StatusName = "Đang chờ xử lý"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2022, 11, 11, 14, 25, 25, 688, DateTimeKind.Local).AddTicks(5155),
                            StatusName = "Đang lấy hàng"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2022, 11, 11, 14, 25, 25, 688, DateTimeKind.Local).AddTicks(5155),
                            StatusName = "Đang giao hàng"
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2022, 11, 11, 14, 25, 25, 688, DateTimeKind.Local).AddTicks(5155),
                            StatusName = "Giao hàng thành công"
                        });
                });

            modelBuilder.Entity("DACS2.Data.Entities.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Supplier");
                });

            modelBuilder.Entity("DACS2.Data.Entities.SysTempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("System");
                });

            modelBuilder.Entity("DACS2.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdRole")
                        .HasColumnType("int");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdRole");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DetleteBy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DislayOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VoucherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<int?>("percent")
                        .HasColumnType("int");

                    b.Property<int?>("price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Voucher");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Color", b =>
                {
                    b.HasOne("DACS2.Data.Entities.Product", "product")
                        .WithMany("colors")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Designs", b =>
                {
                    b.HasOne("DACS2.Data.Entities.Product", "product")
                        .WithMany("designs")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Image", b =>
                {
                    b.HasOne("DACS2.Data.Entities.Product", "Product")
                        .WithMany("images")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Invoice", b =>
                {
                    b.HasOne("DACS2.Data.Entities.Status", "status")
                        .WithMany("invoices")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("status");
                });

            modelBuilder.Entity("DACS2.Data.Entities.InvoiceDetails", b =>
                {
                    b.HasOne("DACS2.Data.Entities.Invoice", "invoice")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("IdInvoice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("invoice");
                });

            modelBuilder.Entity("DACS2.Data.Entities.News", b =>
                {
                    b.HasOne("DACS2.Data.Entities.CategoryNews", "categoryNews")
                        .WithMany("news")
                        .HasForeignKey("IdCategoryNew")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoryNews");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Product", b =>
                {
                    b.HasOne("DACS2.Data.Entities.CategoryProduct", "categoryProduct")
                        .WithMany("Products")
                        .HasForeignKey("IdProductCategory")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS2.Data.Entities.Supplier", "supplier")
                        .WithMany("products")
                        .HasForeignKey("IdSuplier")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoryProduct");

                    b.Navigation("supplier");
                });

            modelBuilder.Entity("DACS2.Data.Entities.RolePermission", b =>
                {
                    b.HasOne("DACS2.Data.Entities.MstPerMission", "mstPerMission")
                        .WithMany("rolePermissions")
                        .HasForeignKey("MStPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACS2.Data.Entities.Role", "role")
                        .WithMany("rolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mstPerMission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Size", b =>
                {
                    b.HasOne("DACS2.Data.Entities.Product", "product")
                        .WithMany("sizes")
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("DACS2.Data.Entities.User", b =>
                {
                    b.HasOne("DACS2.Data.Entities.Role", "role")
                        .WithMany("Users")
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("DACS2.Data.Entities.CategoryNews", b =>
                {
                    b.Navigation("news");
                });

            modelBuilder.Entity("DACS2.Data.Entities.CategoryProduct", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Invoice", b =>
                {
                    b.Navigation("InvoiceDetails");
                });

            modelBuilder.Entity("DACS2.Data.Entities.MstPerMission", b =>
                {
                    b.Navigation("rolePermissions");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Product", b =>
                {
                    b.Navigation("colors");

                    b.Navigation("designs");

                    b.Navigation("images");

                    b.Navigation("sizes");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");

                    b.Navigation("rolePermissions");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Status", b =>
                {
                    b.Navigation("invoices");
                });

            modelBuilder.Entity("DACS2.Data.Entities.Supplier", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
